<?xml version="1.0"?>
<algebra>
  <basicAlgebra>
    <algName>test3</algName>
    <desc>an algebra with arity 3</desc>
    <cardinality>3</cardinality>
    <operations>
      <op>
        <opSymbol>
          <opName>test</opName>
          <arity>3</arity>
        </opSymbol>
        <opTable>
          <intArray>
            <row r="[0,0]">2,0,2</row>
            <row r="[0,1]">1,2,2</row>
            <row r="[0,2]">1,1,1</row>
            <row r="[1,0]">2,1,1</row>
            <row r="[1,1]">0,2,0</row>
            <row r="[1,2]">0,1,2</row>
            <row r="[2,0]">1,1,1</row>
            <row r="[2,1]">1,1,1</row>
            <row r="[2,2]">0,0,2</row>
          </intArray>
        </opTable>
      </op>
    </operations>
  </basicAlgebra>
</algebra>
