<?xml version="1.0"?>
<algebra>
  <basicAlgebra>
    <algName>test</algName>
    <cardinality>5</cardinality>
    <operations>
      <op>
        <opSymbol>
          <opName>e</opName>
          <arity>0</arity>
        </opSymbol>
        <opTable>
          <intArray>
            <row>0</row>
          </intArray>
        </opTable>
      </op>
      <op>
        <opSymbol>
          <opName>neg</opName>
          <arity>1</arity>
        </opSymbol>
        <opTable>
          <intArray>
            <row>2,4,3,2,0</row>
          </intArray>
        </opTable>
      </op>
      <op>
        <opSymbol>
          <opName>dot</opName>
          <arity>2</arity>
        </opSymbol>
        <opTable>
          <intArray>
            <row r="[0]">2,0,1,0,4</row>
            <row r="[1]">2,4,2,1,3</row>
            <row r="[2]">3,3,4,2,1</row>
            <row r="[3]">1,3,3,4,0</row>
            <row r="[4]">0,0,0,1,4</row>
          </intArray>
        </opTable>
      </op>
      <op>
        <opSymbol>
          <opName>R</opName>
          <arity>3</arity>
        </opSymbol>
        <opTable>
          <intArray>
            <row r="[0,0]">0,0,2,2,4</row>
            <row r="[0,1]">1,0,2,0,4</row>
            <row r="[0,2]">1,3,0,1,1</row>
            <row r="[0,3]">2,3,2,3,3</row>
            <row r="[0,4]">3,3,2,1,1</row>
            <row r="[1,0]">3,3,1,3,4</row>
            <row r="[1,1]">0,3,0,1,2</row>
            <row r="[1,2]">3,1,1,0,2</row>
            <row r="[1,3]">4,4,1,0,4</row>
            <row r="[1,4]">0,0,1,0,2</row>
            <row r="[2,0]">3,0,1,4,1</row>
            <row r="[2,1]">1,3,1,4,1</row>
            <row r="[2,2]">2,1,3,1,0</row>
            <row r="[2,3]">4,4,2,0,1</row>
            <row r="[2,4]">2,0,4,3,0</row>
            <row r="[3,0]">3,4,1,3,3</row>
            <row r="[3,1]">0,1,3,4,0</row>
            <row r="[3,2]">0,4,2,4,1</row>
            <row r="[3,3]">1,2,4,3,3</row>
            <row r="[3,4]">2,4,2,0,1</row>
            <row r="[4,0]">1,1,2,1,4</row>
            <row r="[4,1]">2,0,0,3,2</row>
            <row r="[4,2]">1,4,3,2,3</row>
            <row r="[4,3]">2,4,3,2,0</row>
            <row r="[4,4]">1,0,3,2,4</row>
          </intArray>
        </opTable>
      </op>
    </operations>
  </basicAlgebra>
</algebra>
